pipeline {
	agent any
	tools{ maven 'mvn-3.3.9' }
	stages {
		stage ('Initialize') { steps { sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' } }
		stage('Checkout SCM') { steps { checkout scm } }

		stage('Code Analysis && Build') {
			steps {
				withSonarQubeEnv('sonarQB') {
					sh "mvn clean install -Dmaven.test.skip=true "
					sh 'sleep 10'
				}
			}
		}
		stage('Build Docker image') {
			/* This builds the actual image; synonymous to
			 * docker build on the command line */
			steps {
				script {
					
					sh "cp target/*.jar /home/turja/DevOps/SampleApp/dockerfile/"
					
					dir ("/home/turja/DevOps/SampleApp/dockerfile" )
					{
					
						def app = docker.build("dev-image:${env.BUILD_ID}" )
					}
					
				}
				
			}
		}
		stage('Run Docker image') {
			/* This builds the actual image; synonymous to
			 * docker build on the command line */
			steps {
				script {
					
					DOCKER_IMAGE  =   "dev-image:${env.BUILD_ID}"
					
					echo "Docker Image = ${DOCKER_IMAGE}"
					
					sh "nohup docker run -p8080:8080  ${DOCKER_IMAGE}"
					
					//app.inside { sh 'mvn test' }
				}
				// post { always { junit 'target/surefire-reports/*.xml' } }
			}
		}
	}
}

