pipeline {
	agent any
	tools{
		maven 'mvn-3.3.9'
	}
	stages 
	{
		stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
	   stage('Checkout') 
	   {
	   steps {
	   		checkout scm   
	   	}
	   }
	   
	   stage('Build') 
	   {  
		steps {
	  		sh "mvn clean install -Dmaven.test.skip=true"
	  	}
       }
		
	   stage('Test') 
	   { 
        steps {
            sh 'mvn test' 
        }   
	      post {
	        always {
	            junit 'target/surefire-reports/*.xml'
	        }
	     }
       }
	}
}